In [1]:
import numpy as np

# Note about "rank 1 array"
In numpy we have an array which has a dimension of `(n,)` where *n* is any positive integer. This type of array is called *rank 1 array*

### Example: 1

In [3]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)

[1 2 3]
(3,)


*Rank 1 array* are created when we pass a list as an argument to `.array()` method. These *rank 1 array* nethier functions as a vector (row or column matrix) nor as a matrix. <b>We have to avoid using *rank 1 array*</b>

To avoid *rank 1 array* pass a list of lists as an arrugment to `.array()` method, where each inner list represent a single row of matrix

### Example: 2

In [4]:
b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


### Example: 3

In [5]:
c = np.array([[1, 2, 3],
             [4, 5, 6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


Observe that in example 2 there is only one inner list which means there would be only one row in our matrix. Similarly, in example 3 we have two inner lists which means there would be three rows in our matrix