In [1]:
import numpy as np

# Note about "rank 1 array"
In numpy we have an array which has a dimension of `(n,)` where *n* is any positive integer. This type of array is called *rank 1 array*

### Example: 1

In [3]:
a = np.array([1, 2, 3])
print(a)
print(a.shape)

[1 2 3]
(3,)


*Rank 1 array* are created when we pass a list as an argument to `.array()` method. These *rank 1 array* nethier functions as a vector (row or column matrix) nor as a matrix. <b>We have to avoid using *rank 1 array*</b>

To avoid *rank 1 array* pass a list of lists as an arrugment to `.array()` method, where each inner list represent a single row of matrix

### Example: 2

In [4]:
b = np.array([[1, 2, 3]])
print(b)
print(b.shape)

[[1 2 3]]
(1, 3)


### Example: 3

In [5]:
c = np.array([[1, 2, 3],
             [4, 5, 6]])
print(c)
print(c.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


Observe that in example 2 there is only one inner list which means there would be only one row in our matrix. Similarly, in example 3 we have two inner lists which means there would be three rows in our matrix

# Finding Exponent ($ e^x $)

`np.exp()` is used to find exponent in numpy module. Python math module also have to function for this purpose which is `math.exp()` but this is rarely used in ML/DL because it takes a real number while `np.exp()` can be applied to every element of a whole vector or matrix

In [3]:
x = np.array([[1],
             [2],
             [3]])
print(np.exp(x))

[[ 2.71828183]
 [ 7.3890561 ]
 [20.08553692]]


The shape of output from `np.exp()` would be identical to the argument provided. Observe in above example we provided a column matrix to `np.exp()` so it also output a column matrix as result

# Populating With Zeros
`.zeros()` method is used to create matrix containing zeros

## .1) Rank 1 Array
Rank 1 array of zeros can be declared in multiple ways

In [18]:
my_arr1 = np.zeros(5)
print(my_arr1)
print(my_arr1.shape)

[0. 0. 0. 0. 0.]
(5,)


In [20]:
my_arr2 = np.zeros([5])
print(my_arr2)
print(my_arr2.shape)

[0. 0. 0. 0. 0.]
(5,)


In [21]:
my_arr3 = np.zeros((5))
print(my_arr3)
print(my_arr3.shape)

[0. 0. 0. 0. 0.]
(5,)


Observe the little difference (first takes integer, second takes list, third takes tuple) in initializing different arrays but all have same elements and shape

But we have to avoid using rank 1 array so we won't be using above methods

## .2) Vector or Matrix
Row vector, column vector or matrix of any shape can be defined either by passing a list or tuple to `.zeros()` method **having multiple elements** (if or list or tuple have only one element, a rank 1 array would be created)

In [22]:
print(np.zeros([1, 3]))  # Row vector
print(np.zeros([1, 3]).shape)

[[0. 0. 0.]]
(1, 3)


In [23]:
print(np.zeros([3, 1]))  # Column vector
print(np.zeros([3, 1]).shape)

[[0.]
 [0.]
 [0.]]
(3, 1)


In [24]:
print(np.zeros([2, 3]))  # 2D matrix 
print(np.zeros([2, 3]).shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [25]:
print(np.zeros([2, 3, 2]))  # 3D matrix 
print(np.zeros([2, 3, 2]).shape)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
(2, 3, 2)


In [26]:
print(np.zeros((2, 3, 2)))  # 3D matrix but this time passing a tuple

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


Observe that passing tuple or list as an argument doesn't make any difference. Make one convention and remember it. Try to pass list as `np.array()` also takes list of list